name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npx ng build ngx-kit-ui

      - name: Publish to GPR
        run: npm publish ./dist/ngx-kit-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
